AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fixed Sandbox Lab: DB in Protected Public Subnet for Install Access'

Resources:
  # --- NETWORK ---
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: [{Key: Name, Value: BookstoreVPC}]

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-east-1a
      Tags: [{Key: Name, Value: Public Subnet}]

  # --- ROUTING ---
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # --- SECURITY GROUPS (The Real Protection) ---
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH from Internet
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SQL only from Web Server (Strict!)
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        # ONLY allows traffic from the Web Server. No Public Internet access allowed Inbound.
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          SourceSecurityGroupId: !Ref WebSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref WebSecurityGroup

  # --- DATABASE SERVER (Now in Public Subnet for Install Access) ---
  DBServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      ImageId: ami-0c7217cdde317cfec # Ubuntu 22.04
      SubnetId: !Ref PublicSubnet # <--- MOVED TO PUBLIC FOR INTERNET
      SecurityGroupIds: 
        - !Ref DBSecurityGroup
      KeyName: vockey
      IamInstanceProfile: LabInstanceProfile
      Tags: [{Key: Name, Value: BookstoreDBServer}]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Now this will work because we have Internet!
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"
          sudo apt-get update
          sudo apt-get install -y mssql-server
          
          # Configure SQL Server silently
          sudo MSSQL_SA_PASSWORD='StrongAdminPass123!' \
               MSSQL_PID='express' \
               /opt/mssql/bin/mssql-conf -n setup accept-eula

          # Create Audit Directory
          sudo mkdir -p /var/opt/mssql/audit
          sudo chown mssql:mssql /var/opt/mssql/audit

  # --- WEB SERVER ---
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c7217cdde317cfec
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds: 
        - !Ref WebSecurityGroup
      KeyName: vockey
      IamInstanceProfile: LabInstanceProfile
      Tags: [{Key: Name, Value: BookstoreWebServer}]

Outputs:
  WebServerIP:
    Description: Public IP of Web Server
    Value: !GetAtt WebServer.PublicIp
  DBPrivateIP:
    Description: Private IP of Database (Use this in .env)
    Value: !GetAtt DBServer.PrivateIp
